name: TESTING THE GRID
favicon: null
layout_spectrum: 0.6472674962133169
typography_spectrum: 0.44622045080177486
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8263966855593026
  lightness: 0.6666167206130922
  saturation: 0.208055050810799
  rhythmicContrast: 0.9491000284906477
purpose: []
